// ============================================================
// Future Stock Buyer — App Data
// ============================================================

const SECTORS = [
  { id: "ai", label: "AI & Machine Learning", icon: "🤖", color: "#F59E0B" },
  { id: "biotech", label: "Biotech & Genomics", icon: "🧬", color: "#10B981" },
  { id: "fintech", label: "Fintech & Payments", icon: "💳", color: "#3B82F6" },
  { id: "ev", label: "EV & Clean Energy", icon: "⚡", color: "#6EE7B7" },
  { id: "space", label: "Space & Aerospace", icon: "🚀", color: "#8B5CF6" },
  { id: "cybersec", label: "Cybersecurity", icon: "🔒", color: "#EF4444" },
  { id: "cloud", label: "Cloud & SaaS", icon: "☁️", color: "#60A5FA" },
  { id: "crypto", label: "Crypto & Web3", icon: "₿", color: "#F97316" },
  { id: "health", label: "Digital Health", icon: "🏥", color: "#34D399" },
  { id: "retail", label: "Retail & eCommerce", icon: "🛍️", color: "#EC4899" },
  { id: "defense", label: "Defense & Security", icon: "🛡️", color: "#64748B" },
  { id: "robotics", label: "Robotics & Automation", icon: "🦾", color: "#A78BFA" },
  { id: "media", label: "Media & Streaming", icon: "📺", color: "#F43F5E" },
  { id: "food", label: "Food Tech & AgriTech", icon: "🌱", color: "#84CC16" },
  { id: "realestate", label: "PropTech & Real Estate", icon: "🏠", color: "#FB923C" },
  { id: "quantum", label: "Quantum Computing", icon: "⚛️", color: "#C084FC" },
  { id: "logistics", label: "Logistics & Supply Chain", icon: "📦", color: "#94A3B8" },
  { id: "edtech", label: "EdTech & Learning", icon: "🎓", color: "#FCD34D" },
];

const IPO_DATA = {
  ai: [
    {
      id: "openai",
      name: "OpenAI",
      ticker: null,
      sector: "ai",
      valuation: "$157B",
      eta: "Q4 2025",
      etaDate: "2025-12-01",
      status: "Rumored",
      confidence: 72,
      description: "OpenAI, maker of ChatGPT and GPT-4, has been in discussions with investment banks about a potential IPO. CEO Sam Altman has hinted at going public once the company reaches sufficient scale. Microsoft's $13B stake and pressure from early investors could accelerate the timeline significantly.",
      newsHeadline: "OpenAI restructures to for-profit to pave IPO path",
      newsDate: "Apr 28, 2026",
      hype: 98,
      tags: ["LLM", "Consumer AI", "Enterprise"],
    },
    {
      id: "anthropic",
      name: "Anthropic",
      ticker: null,
      sector: "ai",
      valuation: "$61B",
      eta: "2026",
      etaDate: "2026-06-01",
      status: "Exploring",
      confidence: 58,
      description: "Anthropic, the safety-focused AI lab behind Claude, raised $4B from Amazon and has seen rapid enterprise adoption. Backed by Google as well, Anthropic is one of the most likely AI companies to pursue an IPO in 2026 as it seeks additional growth capital.",
      newsHeadline: "Anthropic Claude 4 tops enterprise AI benchmarks",
      newsDate: "May 1, 2026",
      hype: 88,
      tags: ["LLM", "Safety AI", "Enterprise"],
    },
    {
      id: "databricks",
      name: "Databricks",
      ticker: null,
      sector: "ai",
      valuation: "$62B",
      eta: "Q3 2026",
      etaDate: "2026-09-01",
      status: "Filed S-1",
      confidence: 85,
      description: "Databricks, the data + AI platform giant, confidentially filed for an IPO in early 2026. With $2.4B ARR and strong enterprise contracts, it's one of the most anticipated tech IPOs. The company recently acquired MosaicML for $1.3B to boost its AI model training capabilities.",
      newsHeadline: "Databricks hits $2.4B ARR ahead of public offering",
      newsDate: "Apr 30, 2026",
      hype: 91,
      tags: ["Data Platform", "MLOps", "Enterprise"],
    },
    {
      id: "scale_ai",
      name: "Scale AI",
      ticker: null,
      sector: "ai",
      valuation: "$29B",
      eta: "Q1 2027",
      etaDate: "2027-03-01",
      status: "Watching",
      confidence: 44,
      description: "Scale AI provides data labeling and AI infrastructure to the US government and major tech firms. Its $1B contract with the US Department of Defense and partnerships with OpenAI, Meta, and Microsoft position it as critical AI infrastructure. IPO discussions reportedly started in late 2025.",
      newsHeadline: "Scale AI wins $500M Pentagon AI contract expansion",
      newsDate: "Apr 22, 2026",
      hype: 76,
      tags: ["Data Labeling", "Government", "Infrastructure"],
    },
    {
      id: "perplexity",
      name: "Perplexity AI",
      ticker: null,
      sector: "ai",
      valuation: "$14B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 38,
      description: "Perplexity AI's answer-engine approach to search has attracted 15M+ daily active users and caught the attention of investors including SoftBank. Despite Google's countermoves, Perplexity has carved out a niche among knowledge workers. An IPO is speculative but increasingly discussed.",
      newsHeadline: "Perplexity reaches 15M DAU, eyes enterprise tier launch",
      newsDate: "Apr 18, 2026",
      hype: 70,
      tags: ["Search AI", "Consumer", "Knowledge"],
    },
  ],
  biotech: [
    {
      id: "alto_neuroscience",
      name: "Alto Neuroscience",
      ticker: null,
      sector: "biotech",
      valuation: "$3.2B",
      eta: "Q2 2026",
      etaDate: "2026-06-15",
      status: "Filed S-1",
      confidence: 78,
      description: "Alto Neuroscience uses AI-driven biomarker profiling to personalize psychiatric treatments. Its lead compound ALTO-300 showed strong Phase 2 results for treatment-resistant depression. The company raised $200M Series C in 2025 and is considered one of the most innovative CNS-focused biotechs.",
      newsHeadline: "Alto Neuroscience ALTO-300 Phase 2 shows 60% response rate",
      newsDate: "Apr 25, 2026",
      hype: 82,
      tags: ["CNS", "Precision Medicine", "AI Drug"],
    },
    {
      id: "isomorphic_labs",
      name: "Isomorphic Labs",
      ticker: null,
      sector: "biotech",
      valuation: "$4.5B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Rumored",
      confidence: 45,
      description: "Spun out of DeepMind, Isomorphic Labs applies AlphaFold technology to drug discovery. With partnerships with Eli Lilly and Novartis worth $2.9B, the company is generating real revenue from AI-designed drugs. A spinout IPO is speculated as Google diversifies its life sciences portfolio.",
      newsHeadline: "Isomorphic Labs accelerates Eli Lilly oncology pipeline",
      newsDate: "Apr 10, 2026",
      hype: 88,
      tags: ["AI Drug Discovery", "Protein Folding", "Oncology"],
    },
    {
      id: "tempus_ai",
      name: "Tempus AI",
      ticker: "TEM",
      sector: "biotech",
      etaDate: "2024-06-12",
      ipoDate: "June 12, 2024",
      status: "Recently IPO'd",
      ipoPrice: 37,
      currentPrice: 51.2,
      valuation: "$8.1B",
      eta: "IPO'd June 2024",
      confidence: 100,
      description: "Tempus AI went public in June 2024 at $37/share, raising $410M. The genomic data and AI diagnostics company now trades under TEM and has partnerships with AstraZeneca and Google.",
      newsHeadline: "Tempus AI expands AI diagnostics partnership with AstraZeneca",
      newsDate: "May 2, 2026",
      hype: 74,
      tags: ["Genomics", "Diagnostics", "AI"],
    },
    {
      id: "recursion_pharma",
      name: "Recursion Pharmaceuticals",
      ticker: "RXRX",
      sector: "biotech",
      valuation: "$3.4B",
      eta: "Listed",
      etaDate: "2023-04-14",
      status: "Listed",
      confidence: 100,
      description: "Recursion uses AI and automation to discover new drugs at unprecedented speed. Recently acquired Exscientia for $688M to create one of the largest AI drug discovery platforms. Partnership with Nvidia for drug discovery computing is a key differentiator.",
      newsHeadline: "Recursion-Nvidia drug discovery platform launches Phase 1",
      newsDate: "Apr 29, 2026",
      hype: 68,
      tags: ["Drug Discovery", "Automation", "Nvidia"],
    },
    {
      id: "xaira",
      name: "Xaira Therapeutics",
      ticker: null,
      sector: "biotech",
      valuation: "$2.4B",
      eta: "Q4 2027",
      etaDate: "2027-10-01",
      status: "Watching",
      confidence: 35,
      description: "Xaira Therapeutics launched in 2024 with $1B in funding to build generative AI models for drug design. Founded by Marc Tessier-Lavigne, the company is developing entirely AI-generated small molecule drugs — a still-unproven but potentially revolutionary approach.",
      newsHeadline: "Xaira files IND for first wholly AI-designed drug candidate",
      newsDate: "Mar 31, 2026",
      hype: 79,
      tags: ["Generative AI", "Small Molecule", "Novel Targets"],
    },
  ],
  fintech: [
    {
      id: "stripe",
      name: "Stripe",
      ticker: null,
      sector: "fintech",
      valuation: "$70B",
      eta: "Q2 2026",
      etaDate: "2026-06-01",
      status: "Filed S-1",
      confidence: 88,
      description: "Stripe, the global payments giant, has been the most anticipated fintech IPO for years. With $1T+ in payment volume, 500K+ business customers, and recent profitability, it is finally ready. Confidential S-1 was filed in early 2026 after CEO Patrick Collison signaled readiness.",
      newsHeadline: "Stripe confidentially files S-1, Goldman Sachs leading",
      newsDate: "Apr 15, 2026",
      hype: 97,
      tags: ["Payments", "Infrastructure", "Global"],
    },
    {
      id: "chime",
      name: "Chime",
      ticker: null,
      sector: "fintech",
      valuation: "$25B",
      eta: "Q3 2026",
      etaDate: "2026-09-01",
      status: "Exploring",
      confidence: 62,
      description: "Chime, America's largest neobank with 22M+ customers, has been exploring an IPO since 2021 but delayed multiple times. With improved unit economics, reduced churn, and a profitable 2025, the conditions are finally ripe. Chime's lack of traditional banking license remains a regulatory question.",
      newsHeadline: "Chime reports first profitable year, eyes 2026 listing",
      newsDate: "Apr 5, 2026",
      hype: 80,
      tags: ["Neobank", "Consumer", "Banking"],
    },
    {
      id: "klarna",
      name: "Klarna",
      ticker: null,
      sector: "fintech",
      valuation: "$15B",
      eta: "Q2 2026",
      etaDate: "2026-05-20",
      status: "Filed S-1",
      confidence: 92,
      description: "Klarna filed its S-1 with the SEC in late 2025 and is targeting a US listing in mid-2026. The Swedish BNPL giant has rebuilt profitability after a dramatic valuation cut and is now generating strong margins. Sebastian Siemiatkowski has been vocal about the IPO being imminent.",
      newsHeadline: "Klarna confirms NYSE listing target for June 2026",
      newsDate: "May 2, 2026",
      hype: 86,
      tags: ["BNPL", "Payments", "European"],
    },
    {
      id: "plaid",
      name: "Plaid",
      ticker: null,
      sector: "fintech",
      valuation: "$6B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Watching",
      confidence: 42,
      description: "Plaid, the financial data network powering apps like Venmo and Robinhood, escaped Visa's blocked acquisition and has been building independently. With open banking regulations expanding, Plaid's API-first model is gaining traction. An IPO in 2027 is increasingly realistic.",
      newsHeadline: "Plaid integrates with 12,000 financial institutions globally",
      newsDate: "Apr 19, 2026",
      hype: 71,
      tags: ["Open Banking", "API", "Infrastructure"],
    },
    {
      id: "brex",
      name: "Brex",
      ticker: null,
      sector: "fintech",
      valuation: "$12.3B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 40,
      description: "Brex pivoted from consumer to enterprise spend management and has seen strong growth with its AI-powered expense platform. With 20,000+ business customers and $500M ARR, Brex is a candidate for a mid-2027 IPO as the market environment improves.",
      newsHeadline: "Brex AI expense platform sees 40% YoY growth in enterprise",
      newsDate: "Apr 11, 2026",
      hype: 65,
      tags: ["Corporate Cards", "Expense Mgmt", "Enterprise"],
    },
  ],
  ev: [
    {
      id: "northvolt",
      name: "Northvolt",
      ticker: null,
      sector: "ev",
      valuation: "$5.2B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Restructuring",
      confidence: 35,
      description: "European battery giant Northvolt filed for Chapter 11 in late 2024 but emerged with new financing from Volkswagen and BMW. The restructured company is targeting gigafactory scale by 2026 and eyeing a Stockholm or US dual listing in 2027 pending financial recovery.",
      newsHeadline: "Northvolt exits bankruptcy with $1.2B in new funding",
      newsDate: "Apr 8, 2026",
      hype: 60,
      tags: ["Battery", "European", "EV Supply"],
    },
    {
      id: "ampere",
      name: "Ampere (Renault EV)",
      ticker: null,
      sector: "ev",
      valuation: "$8.5B",
      eta: "Q4 2026",
      etaDate: "2026-11-01",
      status: "Exploring",
      confidence: 55,
      description: "Renault's EV spinoff Ampere is targeting a Euronext listing in late 2026 after pausing earlier IPO plans. With the R5 EV selling strongly and new partnerships with Volkswagen, Ampere has rebuilt investor confidence and is one of Europe's most watched EV IPOs.",
      newsHeadline: "Ampere R5 crosses 100,000 orders, EU IPO back on track",
      newsDate: "Apr 20, 2026",
      hype: 72,
      tags: ["European EV", "Renault", "Mass Market"],
    },
    {
      id: "solid_power",
      name: "Solid Power",
      ticker: "SLDP",
      sector: "ev",
      valuation: "$1.1B",
      eta: "Listed",
      etaDate: "2021-12-09",
      status: "Listed",
      confidence: 100,
      description: "Solid Power went public via SPAC in late 2021 and is developing solid-state batteries for EVs. Partners include BMW and Ford. EV solid-state batteries remain the industry's holy grail — Solid Power is one of the few publicly traded pure-play contenders.",
      newsHeadline: "Solid Power achieves 500+ Wh/kg in solid-state cell tests",
      newsDate: "Apr 24, 2026",
      hype: 78,
      tags: ["Solid State", "Battery Tech", "BMW/Ford"],
    },
    {
      id: "zeekr",
      name: "Zeekr",
      ticker: "ZK",
      sector: "ev",
      valuation: "$6.8B",
      eta: "Listed",
      etaDate: "2024-05-10",
      status: "Listed",
      confidence: 100,
      description: "Zeekr, Geely's premium EV brand, listed on NYSE in May 2024. Known for ultra-fast 800V charging and long range, it's competing directly with Tesla's Model S in China and expanding to Europe.",
      newsHeadline: "Zeekr launches right-hand-drive 001 for UK and Australia",
      newsDate: "Apr 27, 2026",
      hype: 67,
      tags: ["China EV", "Premium", "Geely"],
    },
    {
      id: "zeroavia",
      name: "ZeroAvia",
      ticker: null,
      sector: "ev",
      valuation: "$1.8B",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 28,
      description: "ZeroAvia is developing hydrogen-electric powertrains for commercial aviation. Already flying 19-seat aircraft on hydrogen, the company targets 40-80 seat aircraft by 2028. United Airlines is a strategic investor. Commercial scale and regulatory approvals are key IPO milestones.",
      newsHeadline: "ZeroAvia completes first hydrogen-powered regional flight",
      newsDate: "Mar 15, 2026",
      hype: 74,
      tags: ["Hydrogen", "Aviation", "Clean Energy"],
    },
  ],
  space: [
    {
      id: "spacex_starlink",
      name: "SpaceX / Starlink",
      ticker: null,
      sector: "space",
      valuation: "$350B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Rumored",
      confidence: 48,
      description: "While full SpaceX IPO is unlikely under Elon Musk, a Starlink subsidiary IPO has been discussed for years. With 4M+ subscribers, $6.6B in Starlink revenue in 2024, and expansion to maritime and aviation, a carve-out IPO in 2027 is seen as the most likely scenario.",
      newsHeadline: "Starlink reaches 4M subscribers, aviation vertical booming",
      newsDate: "May 1, 2026",
      hype: 96,
      tags: ["Satellite Internet", "Starlink", "Global"],
    },
    {
      id: "relativity_space",
      name: "Relativity Space",
      ticker: null,
      sector: "space",
      valuation: "$4.2B",
      eta: "Q3 2027",
      etaDate: "2027-09-01",
      status: "Watching",
      confidence: 38,
      description: "Relativity Space is 3D-printing entire rockets and building the Terran R — a fully reusable medium-lift launch vehicle. After Terran 1's failed orbital attempt, Terran R represents a major leap. Backlog of $1.7B from the US Space Force and commercial operators supports an eventual IPO.",
      newsHeadline: "Relativity Space Terran R completes engine static fire",
      newsDate: "Apr 12, 2026",
      hype: 80,
      tags: ["Launch Vehicles", "3D Printing", "Reusable"],
    },
    {
      id: "ast_spacemobile",
      name: "AST SpaceMobile",
      ticker: "ASTS",
      sector: "space",
      valuation: "$6.2B",
      eta: "Listed",
      etaDate: "2021-04-08",
      status: "Listed",
      confidence: 100,
      description: "AST SpaceMobile went public via SPAC in 2021 and is building the first space-based cellular broadband network. BlueBird commercial satellites launched in 2024 are now providing direct-to-cell service through AT&T and Verizon partnerships.",
      newsHeadline: "AST SpaceMobile enables first video call from space-based cell",
      newsDate: "Apr 30, 2026",
      hype: 88,
      tags: ["Direct-to-Cell", "Satellite", "Telco"],
    },
    {
      id: "k2_space",
      name: "K2 Space",
      ticker: null,
      sector: "space",
      valuation: "$750M",
      eta: "2028",
      etaDate: "2028-06-01",
      status: "Watching",
      confidence: 25,
      description: "K2 Space is building the largest geostationary satellites ever conceived — 10,000 kg platforms that can be rapidly deployed. Founded by ex-SpaceX engineers with DARPA contracts, K2 is developing infrastructure for the next wave of space-based services including solar power.",
      newsHeadline: "K2 Space wins DARPA contract for mega-satellite platform",
      newsDate: "Feb 28, 2026",
      hype: 72,
      tags: ["Geostationary", "DARPA", "Mega-Satellite"],
    },
    {
      id: "vast_space",
      name: "Vast Space",
      ticker: null,
      sector: "space",
      valuation: "$2.1B",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 30,
      description: "Vast Space is building Haven-1, the first commercial space station, launching on SpaceX Falcon 9 in 2026. Backed by Jed McCaleb, the company aims to become the ISS successor with NASA's blessing. An IPO would likely follow first crewed operations.",
      newsHeadline: "Vast Space Haven-1 launch scheduled for August 2026",
      newsDate: "Apr 17, 2026",
      hype: 85,
      tags: ["Space Station", "Commercial", "NASA"],
    },
  ],
  cybersec: [
    {
      id: "wiz",
      name: "Wiz",
      ticker: null,
      sector: "cybersec",
      valuation: "$32B",
      eta: "Q1 2026",
      etaDate: "2026-03-15",
      status: "Filed S-1",
      confidence: 90,
      description: "Wiz, the cloud security unicorn, rejected Google's $23B acquisition offer and is now aggressively pursuing an IPO. With $500M ARR growing 80% YoY and customers including 40% of the Fortune 100, Wiz is the most hotly anticipated cybersecurity IPO in years.",
      newsHeadline: "Wiz hits $500M ARR, appoints JPMorgan for IPO process",
      newsDate: "May 1, 2026",
      hype: 94,
      tags: ["Cloud Security", "CNAPP", "Enterprise"],
    },
    {
      id: "snyk",
      name: "Snyk",
      ticker: null,
      sector: "cybersec",
      valuation: "$7.4B",
      eta: "Q3 2026",
      etaDate: "2026-09-01",
      status: "Exploring",
      confidence: 58,
      description: "Snyk's developer-first security platform is widely used in DevSecOps pipelines. After a down round in 2022, the company rebuilt to $300M ARR and is exploring a 2026 IPO. AI-powered code security via DeepCode AI has become its key differentiator.",
      newsHeadline: "Snyk DeepCode AI catches 40% more vulnerabilities than rivals",
      newsDate: "Apr 23, 2026",
      hype: 75,
      tags: ["DevSecOps", "Code Security", "Developer"],
    },
    {
      id: "armis",
      name: "Armis Security",
      ticker: null,
      sector: "cybersec",
      valuation: "$4.2B",
      eta: "2027",
      etaDate: "2027-03-01",
      status: "Watching",
      confidence: 45,
      description: "Armis focuses on agentless asset intelligence and OT/IoT security — a fast-growing segment as industrial systems face increasing cyber threats. With $250M ARR and strong government contracts, Armis is a quiet but serious IPO candidate.",
      newsHeadline: "Armis wins $200M US critical infrastructure security contract",
      newsDate: "Apr 7, 2026",
      hype: 68,
      tags: ["IoT Security", "OT/ICS", "Government"],
    },
    {
      id: "lacework",
      name: "Lacework",
      ticker: null,
      sector: "cybersec",
      valuation: "$3.5B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 40,
      description: "Lacework's cloud security platform uses behavioral analytics to detect threats. After a tumultuous 2022-2023, the company stabilized under new leadership and is generating $200M+ ARR. A cautious 2027 IPO is possible if cloud security M&A doesn't claim it first.",
      newsHeadline: "Lacework reports strongest Q1 sales since 2021 peak",
      newsDate: "Apr 14, 2026",
      hype: 58,
      tags: ["Cloud Security", "Behavioral Analytics", "CSPM"],
    },
    {
      id: "cyera",
      name: "Cyera",
      ticker: null,
      sector: "cybersec",
      valuation: "$3.0B",
      eta: "Q2 2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 42,
      description: "Cyera is the leader in AI-powered data security posture management (DSPM), helping enterprises understand and protect sensitive data in the cloud. With $300M raised and customers like Goldman Sachs and Pfizer, Cyera is on a fast track to IPO readiness.",
      newsHeadline: "Cyera raises $300M Series D at $3B valuation for DSPM expansion",
      newsDate: "Mar 22, 2026",
      hype: 72,
      tags: ["DSPM", "Data Security", "AI"],
    },
  ],
  cloud: [
    {
      id: "coreweave",
      name: "CoreWeave",
      ticker: "CRWV",
      sector: "cloud",
      valuation: "$23B",
      eta: "Listed March 2025",
      etaDate: "2025-03-28",
      status: "Listed",
      confidence: 100,
      ipoPrice: 40,
      currentPrice: 54.8,
      description: "CoreWeave, the AI cloud infrastructure company, IPO'd in March 2025 at $40/share. The company provides GPU cloud computing to AI labs including OpenAI and Microsoft. Post-IPO it has seen strong revenue growth driven by AI training demand.",
      newsHeadline: "CoreWeave Q1 2026 revenue triples YoY on AI compute surge",
      newsDate: "May 2, 2026",
      hype: 89,
      tags: ["GPU Cloud", "AI Infrastructure", "Microsoft"],
    },
    {
      id: "retool",
      name: "Retool",
      ticker: null,
      sector: "cloud",
      valuation: "$3.2B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Watching",
      confidence: 38,
      description: "Retool's low-code platform for building internal business tools has 100,000+ developers building on it. The company recently launched Retool AI for building AI-powered workflows and saw ARR jump to $200M. Not actively pursuing IPO but increasingly on investors' radar.",
      newsHeadline: "Retool AI workflows see 300% growth in enterprise adoption",
      newsDate: "Apr 2, 2026",
      hype: 65,
      tags: ["Low-Code", "Internal Tools", "AI Workflows"],
    },
    {
      id: "rippling",
      name: "Rippling",
      ticker: null,
      sector: "cloud",
      valuation: "$13.5B",
      eta: "2026",
      etaDate: "2026-12-01",
      status: "Exploring",
      confidence: 60,
      description: "Rippling's HR/IT/Finance platform has achieved $350M ARR with breakneck growth. Parker Conrad's bold vision of a single employee management OS is resonating. The company is exploring a late 2026 or early 2027 IPO, with Goldman Sachs already engaged.",
      newsHeadline: "Rippling hits $350M ARR, expands to payroll in 50 countries",
      newsDate: "Apr 25, 2026",
      hype: 83,
      tags: ["HR Tech", "Platform", "SMB/Enterprise"],
    },
    {
      id: "vercel",
      name: "Vercel",
      ticker: null,
      sector: "cloud",
      valuation: "$3.2B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 35,
      description: "Vercel's frontend cloud platform powers millions of developers and enterprises including McDonald's and TripAdvisor. With Next.js as the dominant React framework and AI-powered v0 code generation, Vercel has diversified its value proposition ahead of a potential IPO.",
      newsHeadline: "Vercel v0 AI code generation surpasses 2M users",
      newsDate: "Apr 16, 2026",
      hype: 74,
      tags: ["Frontend Cloud", "Next.js", "Developer Tools"],
    },
    {
      id: "harness",
      name: "Harness",
      ticker: null,
      sector: "cloud",
      valuation: "$3.7B",
      eta: "2027",
      etaDate: "2027-09-01",
      status: "Watching",
      confidence: 33,
      description: "Harness is the leading AI-native software delivery platform, covering CI/CD, feature flags, cloud cost management, and security testing in one unified suite. With $300M ARR and strong developer community, Harness is positioning for a 2027 IPO.",
      newsHeadline: "Harness AI pipeline reduces deployment times by 70%",
      newsDate: "Apr 3, 2026",
      hype: 62,
      tags: ["DevOps", "CI/CD", "Platform"],
    },
  ],
  crypto: [
    {
      id: "circle",
      name: "Circle Internet",
      ticker: null,
      sector: "crypto",
      valuation: "$9B",
      eta: "Q2 2026",
      etaDate: "2026-05-01",
      status: "Filed S-1",
      confidence: 88,
      description: "Circle, the issuer of USDC stablecoin, filed its S-1 in January 2026. With $1.7B in revenue from interest on USDC reserves and $60B+ in USDC circulation, Circle is one of the clearest crypto business models heading to market in the post-FTX regulatory clarity era.",
      newsHeadline: "Circle S-1 reveals $1.7B revenue, targets NYSE listing",
      newsDate: "Apr 28, 2026",
      hype: 90,
      tags: ["Stablecoin", "USDC", "Payments"],
    },
    {
      id: "kraken",
      name: "Kraken",
      ticker: null,
      sector: "crypto",
      valuation: "$11B",
      eta: "Q4 2026",
      etaDate: "2026-10-01",
      status: "Exploring",
      confidence: 65,
      description: "Kraken, one of the oldest and most trusted crypto exchanges, has been exploring an IPO for years. With SEC's crypto stance softening under the new administration, Kraken (which recently settled with the SEC) is now actively preparing for a potential late 2026 public offering.",
      newsHeadline: "Kraken hires Goldman Sachs for IPO preparation, sources say",
      newsDate: "Apr 20, 2026",
      hype: 82,
      tags: ["Exchange", "Spot Trading", "Regulated"],
    },
    {
      id: "chainalysis",
      name: "Chainalysis",
      ticker: null,
      sector: "crypto",
      valuation: "$8.6B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Watching",
      confidence: 48,
      description: "Chainalysis is the leading blockchain data and compliance company, used by 70+ governments and thousands of financial institutions to track crypto transactions. With regulatory scrutiny increasing globally, its government contract pipeline has never been stronger.",
      newsHeadline: "Chainalysis government contracts reach $200M, adds 15 new nations",
      newsDate: "Apr 10, 2026",
      hype: 70,
      tags: ["Blockchain Analytics", "Compliance", "Government"],
    },
    {
      id: "bitgo",
      name: "BitGo",
      ticker: null,
      sector: "crypto",
      valuation: "$1.75B",
      eta: "2026",
      etaDate: "2026-09-01",
      status: "Exploring",
      confidence: 55,
      description: "BitGo is the dominant institutional crypto custody provider, securing $64B+ in assets for exchanges, banks, and family offices. With new banking regulations allowing crypto custody, BitGo's addressable market has expanded dramatically. IPO preparations are underway.",
      newsHeadline: "BitGo obtains federal bank charter approval for crypto custody",
      newsDate: "Apr 5, 2026",
      hype: 68,
      tags: ["Custody", "Institutional", "Banking"],
    },
    {
      id: "moonpay",
      name: "MoonPay",
      ticker: null,
      sector: "crypto",
      valuation: "$3.4B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 38,
      description: "MoonPay is the on/off-ramp for crypto that powers NFT and token purchases for PayPal, Mastercard, and 350+ other platforms. With $150M revenue and celebrity investors, MoonPay is positioning itself as the Stripe of crypto ahead of an eventual IPO.",
      newsHeadline: "MoonPay Mastercard partnership brings crypto to 3B cardholders",
      newsDate: "Mar 18, 2026",
      hype: 65,
      tags: ["On-Ramp", "Payments", "NFT"],
    },
  ],
  health: [
    {
      id: "noom",
      name: "Noom",
      ticker: null,
      sector: "health",
      valuation: "$3.7B",
      eta: "2026",
      etaDate: "2026-10-01",
      status: "Exploring",
      confidence: 48,
      description: "Noom's psychology-based weight management app has pivoted from pure subscription to a GLP-1 medication companion platform, riding the Ozempic wave. With 50M+ users and new clinical partnerships, a 2026 IPO is on the table after a 2022 down round recovery.",
      newsHeadline: "Noom GLP-1 companion sees 3x growth, targets 2026 listing",
      newsDate: "Apr 14, 2026",
      hype: 72,
      tags: ["Weight Loss", "GLP-1 Companion", "Behavioral"],
    },
    {
      id: "hims_hers",
      name: "Brightside Health",
      ticker: null,
      sector: "health",
      valuation: "$2.1B",
      eta: "2027",
      etaDate: "2027-03-01",
      status: "Watching",
      confidence: 38,
      description: "Brightside Health is a full-service mental health platform offering therapy, psychiatry, and crisis support. With AI-driven care coordination and 95% patient satisfaction, it's the leading telehealth mental health provider outside of Cerebral. IPO timing depends on regulatory environment.",
      newsHeadline: "Brightside expands crisis support to all 50 US states",
      newsDate: "Apr 8, 2026",
      hype: 65,
      tags: ["Mental Health", "Teletherapy", "Crisis Care"],
    },
    {
      id: "zipline",
      name: "Zipline International",
      ticker: null,
      sector: "health",
      valuation: "$4.2B",
      eta: "Q1 2027",
      etaDate: "2027-03-01",
      status: "Exploring",
      confidence: 52,
      description: "Zipline delivers medical supplies and goods via autonomous drones in 9 countries, including the US where it's launching same-day delivery in major cities. With contracts from Walmart, Cleveland Clinic, and multiple governments, Zipline is scaling toward IPO readiness.",
      newsHeadline: "Zipline launches same-day drone delivery in Dallas metro",
      newsDate: "Apr 21, 2026",
      hype: 85,
      tags: ["Medical Drones", "Last Mile", "Autonomous"],
    },
    {
      id: "sword_health",
      name: "Sword Health",
      ticker: null,
      sector: "health",
      valuation: "$3B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 42,
      description: "Sword Health's AI physical therapy platform serves 2M+ members through employer health plans. Its AI-only 'Phoenix' model eliminates human PTs for most cases, dramatically reducing costs. This controversial but effective approach has won major enterprise clients.",
      newsHeadline: "Sword Health AI-only PT model adopted by 3 Top-50 US employers",
      newsDate: "Apr 2, 2026",
      hype: 73,
      tags: ["Physical Therapy", "AI Health", "Employer"],
    },
    {
      id: "hims_co",
      name: "Hims & Hers Health",
      ticker: "HIMS",
      sector: "health",
      valuation: "$3.4B",
      eta: "Listed",
      etaDate: "2021-01-21",
      status: "Listed",
      confidence: 100,
      description: "Hims & Hers went public via SPAC in 2021. The telehealth company now sells GLP-1 compounded medications, hair loss treatments, and sexual health products, seeing explosive growth in 2024-2025 on the back of weight loss drug demand.",
      newsHeadline: "Hims & Hers raises FY2026 guidance on GLP-1 growth",
      newsDate: "Apr 30, 2026",
      hype: 78,
      tags: ["Telehealth", "GLP-1", "DTC"],
    },
  ],
  robotics: [
    {
      id: "physical_intelligence",
      name: "Physical Intelligence (π)",
      ticker: null,
      sector: "robotics",
      valuation: "$2.4B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 38,
      description: "Physical Intelligence (π) is building foundation models for robots — essentially the GPT moment for robotic AI. Backed by Jeff Bezos, OpenAI, and Khosla Ventures, its π0 model can fold laundry, cook, and perform complex manipulation tasks. A future IPO would be landmark.",
      newsHeadline: "Physical Intelligence π0 model demonstrated folding laundry autonomously",
      newsDate: "Apr 22, 2026",
      hype: 90,
      tags: ["Robot Foundation Model", "Manipulation", "General Purpose"],
    },
    {
      id: "figure_ai",
      name: "Figure AI",
      ticker: null,
      sector: "robotics",
      valuation: "$2.6B",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 32,
      description: "Figure AI's humanoid robot Figure 02 began working on BMW assembly lines in 2024. With an OpenAI partnership for neural language-driven robot control, Figure is one of the leading humanoid startups. Commercialization at scale is the IPO milestone — expected around 2028.",
      newsHeadline: "Figure 02 completes 1,000-hour autonomous shift at BMW plant",
      newsDate: "Apr 15, 2026",
      hype: 88,
      tags: ["Humanoid", "Manufacturing", "OpenAI"],
    },
    {
      id: "1x_technologies",
      name: "1X Technologies",
      ticker: null,
      sector: "robotics",
      valuation: "$1.1B",
      eta: "2028",
      etaDate: "2028-06-01",
      status: "Watching",
      confidence: 28,
      description: "1X Technologies (backed by OpenAI and Samsung) builds humanoid robots designed for home use. Its NEO robot is designed to assist with household chores and elderly care. The home robotics market is massive but unproven — success could trigger a transformational IPO.",
      newsHeadline: "1X NEO home robot pilot launches in 500 US households",
      newsDate: "Mar 30, 2026",
      hype: 82,
      tags: ["Home Robotics", "Elder Care", "OpenAI"],
    },
    {
      id: "apptronik",
      name: "Apptronik",
      ticker: null,
      sector: "robotics",
      valuation: "$900M",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 25,
      description: "Apptronik's Apollo humanoid robot is partnered with NASA and Mercedes-Benz for warehouse and manufacturing use. The Austin-based company is one of the original humanoid robotics players, tracing its roots to the NASA Valkyrie project.",
      newsHeadline: "Apptronik Apollo begins trial at Mercedes-Benz Alabama plant",
      newsDate: "Apr 4, 2026",
      hype: 76,
      tags: ["Humanoid", "Warehouse", "NASA"],
    },
    {
      id: "agility_robotics",
      name: "Agility Robotics",
      ticker: null,
      sector: "robotics",
      valuation: "$1.75B",
      eta: "2027",
      etaDate: "2027-09-01",
      status: "Watching",
      confidence: 36,
      description: "Agility Robotics' Digit humanoid is the first to be deployed at scale in Amazon fulfillment centers. Its focus on bipedal locomotion in human-designed spaces makes it the most commercially advanced humanoid. A potential IPO could follow Amazon contract expansion.",
      newsHeadline: "Agility Digit deployed in 10 Amazon fulfillment centers nationwide",
      newsDate: "Apr 17, 2026",
      hype: 85,
      tags: ["Humanoid", "Amazon", "Fulfillment"],
    },
  ],
  defense: [
    {
      id: "anduril",
      name: "Anduril Industries",
      ticker: null,
      sector: "defense",
      valuation: "$28B",
      eta: "2026",
      etaDate: "2026-09-01",
      status: "Exploring",
      confidence: 58,
      description: "Anduril, founded by Palmer Luckey, is the most prominent defense tech startup with $22B in government contracts including the US DoD, AUKUS, and NATO allies. Products span autonomous drones, counter-drone systems, and AI-powered command software. IPO readiness is growing.",
      newsHeadline: "Anduril wins $4.2B AUKUS submarine defense contract",
      newsDate: "May 1, 2026",
      hype: 89,
      tags: ["Autonomous Defense", "AUKUS", "AI Military"],
    },
    {
      id: "shield_ai",
      name: "Shield AI",
      ticker: null,
      sector: "defense",
      valuation: "$3B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 45,
      description: "Shield AI's Hivemind AI pilot software enables autonomous swarm drones without GPS or communications. Its Nova UAS is deployed in classified US military operations. With $400M ARR primarily from the DoD, Shield AI is a serious IPO candidate for 2027.",
      newsHeadline: "Shield AI Hivemind deployed in classified CENTCOM operation",
      newsDate: "Apr 9, 2026",
      hype: 80,
      tags: ["Autonomous Drones", "AI Pilot", "Swarm"],
    },
    {
      id: "palantir",
      name: "Palantir Technologies",
      ticker: "PLTR",
      sector: "defense",
      valuation: "$180B",
      eta: "Listed",
      etaDate: "2020-09-30",
      status: "Listed",
      confidence: 100,
      description: "Palantir went public in September 2020 via direct listing. Its AI Platform (AIP) has driven explosive growth in commercial and government sectors. Palantir is increasingly seen as critical AI infrastructure for Western governments.",
      newsHeadline: "Palantir AIP government revenue surges 55% in Q1 2026",
      newsDate: "May 2, 2026",
      hype: 86,
      tags: ["AI Platform", "Government", "Commercial"],
    },
    {
      id: "sarcos_technology",
      name: "Sarcos Technology",
      ticker: null,
      sector: "defense",
      valuation: "$1.2B",
      eta: "2027",
      etaDate: "2027-03-01",
      status: "Watching",
      confidence: 35,
      description: "Sarcos builds full-body powered exoskeletons for industrial and military use. Its Guardian XO exosuit lets workers lift 200lbs repeatedly with minimal fatigue. DoD contracts for soldier augmentation are driving growth ahead of a potential IPO.",
      newsHeadline: "Sarcos Guardian XO approved for Army combat engineer trials",
      newsDate: "Mar 25, 2026",
      hype: 68,
      tags: ["Exoskeleton", "Military", "Industrial"],
    },
    {
      id: "hermeus",
      name: "Hermeus",
      ticker: null,
      sector: "defense",
      valuation: "$1.5B",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 28,
      description: "Hermeus is building Mach 5 hypersonic aircraft for both the US Air Force and commercial passengers. Its Quarterhorse demonstrator achieved sustained Mach 4+ flight in 2025. If successful, Hermeus could revolutionize global travel and military aviation simultaneously.",
      newsHeadline: "Hermeus Quarterhorse achieves Mach 4.5 in sustained test flight",
      newsDate: "Apr 1, 2026",
      hype: 88,
      tags: ["Hypersonic", "Air Force", "Supersonic Travel"],
    },
  ],
  quantum: [
    {
      id: "psiQuantum",
      name: "PsiQuantum",
      ticker: null,
      sector: "quantum",
      valuation: "$6.0B",
      eta: "2027",
      etaDate: "2027-01-01",
      status: "Watching",
      confidence: 38,
      description: "PsiQuantum is building a fault-tolerant photonic quantum computer targeting 1 million qubits. With a $940M investment from the Australian government and partnerships with GlobalFoundries for chip manufacturing, PsiQuantum is the best-funded private quantum computing company.",
      newsHeadline: "PsiQuantum completes first photonic quantum chip factory in Australia",
      newsDate: "Apr 18, 2026",
      hype: 85,
      tags: ["Photonic", "Fault-Tolerant", "1M Qubits"],
    },
    {
      id: "quantinuum",
      name: "Quantinuum",
      ticker: null,
      sector: "quantum",
      valuation: "$5.0B",
      eta: "2026",
      etaDate: "2026-12-01",
      status: "Exploring",
      confidence: 55,
      description: "Quantinuum (formerly Honeywell Quantum) leads in trapped-ion quantum computing and has the highest fidelity commercial quantum computer with 56 qubits. Microsoft recently invested $300M ahead of a potential spin-out IPO, making it one of the most anticipated quantum listings.",
      newsHeadline: "Quantinuum achieves quantum advantage for drug discovery simulation",
      newsDate: "Apr 26, 2026",
      hype: 82,
      tags: ["Trapped Ion", "Microsoft", "Drug Discovery"],
    },
    {
      id: "iqm_quantum",
      name: "IQM Quantum Computers",
      ticker: null,
      sector: "quantum",
      valuation: "$1.2B",
      eta: "2027",
      etaDate: "2027-06-01",
      status: "Watching",
      confidence: 40,
      description: "IQM is the leading European quantum hardware company, building superconducting quantum computers for national labs and governments. With installations in Germany, Finland, and Spain, and growing commercial cloud access, IQM is exploring a European IPO.",
      newsHeadline: "IQM 150-qubit system installed at CERN for physics research",
      newsDate: "Apr 3, 2026",
      hype: 68,
      tags: ["Superconducting", "European", "National Labs"],
    },
    {
      id: "classiq",
      name: "Classiq Technologies",
      ticker: null,
      sector: "quantum",
      valuation: "$500M",
      eta: "2028",
      etaDate: "2028-01-01",
      status: "Watching",
      confidence: 30,
      description: "Classiq provides a software platform that compiles high-level quantum algorithms into optimized quantum circuits — effectively an operating system layer for quantum computing. Its platform supports IBM, Google, and IonQ hardware, making it hardware-agnostic.",
      newsHeadline: "Classiq integrates with Google Willow 105-qubit chip",
      newsDate: "Mar 12, 2026",
      hype: 60,
      tags: ["Quantum Software", "Compiler", "Hardware-Agnostic"],
    },
    {
      id: "atom_computing",
      name: "Atom Computing",
      ticker: null,
      sector: "quantum",
      valuation: "$800M",
      eta: "2028",
      etaDate: "2028-06-01",
      status: "Watching",
      confidence: 28,
      description: "Atom Computing uses neutral atom arrays (the same approach as Harvard's 2023 breakthrough) to achieve record qubit coherence times. Backed by Prelude Ventures, the company demonstrated 1,225 qubits in 2023 and is scaling toward fault tolerance.",
      newsHeadline: "Atom Computing achieves record 2,000-qubit neutral atom array",
      newsDate: "Feb 20, 2026",
      hype: 74,
      tags: ["Neutral Atom", "Record Qubits", "Coherence"],
    },
  ],
};

// ── Logistics & Supply Chain ───────────────────────────────────────────────
IPO_DATA["logistics"] = [
  { id: "flexport", name: "Flexport", ticker: null, sector: "logistics", valuation: "$8B", eta: "2027", etaDate: "2027-06-01", status: "Exploring", confidence: 52, description: "Flexport is the digital freight forwarder that survived a tumultuous 2023 CEO battle. With Ryan Petersen back and AI-driven logistics platform rebuilt, the company is eyeing 2027 IPO after restoring profitability.", newsHeadline: "Flexport AI routing cuts shipping costs 18% for enterprise clients", newsDate: "Apr 22, 2026", hype: 72, tags: ["Freight", "Digital", "Global Trade"] },
  { id: "stord", name: "Stord", ticker: null, sector: "logistics", valuation: "$1.3B", eta: "2027", etaDate: "2027-01-01", status: "Watching", confidence: 38, description: "Stord's cloud supply chain platform connects warehousing, fulfillment, and freight in a single software layer. Backed by BOND and Kleiner Perkins, it's considered the 'Shopify for fulfillment'.", newsHeadline: "Stord lands Coca-Cola as anchor logistics client", newsDate: "Apr 8, 2026", hype: 65, tags: ["Fulfillment", "Cloud", "SMB"] },
  { id: "project44", name: "project44", ticker: null, sector: "logistics", valuation: "$2.7B", eta: "2027", etaDate: "2027-09-01", status: "Watching", confidence: 42, description: "project44's supply chain visibility platform is used by 1,300+ enterprises including Amazon, Walmart, and BMW. Real-time tracking across ocean, air, and ground is its core product.", newsHeadline: "project44 expands ocean freight visibility to 95% of global routes", newsDate: "Apr 15, 2026", hype: 68, tags: ["Visibility", "Enterprise", "Real-time"] },
  { id: "outrider", name: "Outrider", ticker: null, sector: "logistics", valuation: "$900M", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 30, description: "Outrider automates yard operations at distribution centers — the trucks moving trailers between dock doors and parking. A forgotten but massive inefficiency, Outrider has contracts with FedEx and Pepsico.", newsHeadline: "Outrider autonomous yard trucks deployed at 12 FedEx hubs", newsDate: "Mar 20, 2026", hype: 60, tags: ["Autonomous", "Yard Ops", "Distribution"] },
  { id: "loadsmart", name: "Loadsmart", ticker: null, sector: "logistics", valuation: "$1.1B", eta: "2027", etaDate: "2027-03-01", status: "Watching", confidence: 35, description: "Loadsmart's AI freight brokerage platform uses ML to price and match trucking loads automatically. With $150M ARR and profitability in sight, a 2027 IPO could follow the freight market recovery.", newsHeadline: "Loadsmart AI pricing engine achieves 99.2% load tender acceptance", newsDate: "Apr 2, 2026", hype: 58, tags: ["Freight Brokerage", "AI Pricing", "Trucking"] },
];

// ── EdTech & Learning ──────────────────────────────────────────────────────
IPO_DATA["edtech"] = [
  { id: "synthesis", name: "Synthesis", ticker: null, sector: "edtech", valuation: "$500M", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 28, description: "Synthesis, spun out of SpaceX's school for employees' kids, teaches problem-solving through AI-powered collaborative games. Elon Musk's original backing and 300K+ subscribers make it unique.", newsHeadline: "Synthesis hits 300K subscribers, launches AI tutor for adults", newsDate: "Apr 10, 2026", hype: 78, tags: ["AI Tutor", "K-12", "Problem Solving"] },
  { id: "duolingo", name: "Duolingo", ticker: "DUOL", sector: "edtech", valuation: "$7.8B", eta: "Listed", etaDate: "2021-07-28", status: "Listed", ipoPrice: 102, currentPrice: 198, description: "Duolingo went public in July 2021 and has seen strong growth driven by its AI-powered language learning app and Duolingo English Test.", newsHeadline: "Duolingo AI model achieves human-level language coaching benchmark", newsDate: "Apr 28, 2026", hype: 82, confidence: 100, tags: ["Language Learning", "AI", "Consumer"] },
  { id: "coursera_plus", name: "Electives", ticker: null, sector: "edtech", valuation: "$800M", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 33, description: "Electives is a live learning platform for corporate L&D — offering real-time courses from expert instructors rather than pre-recorded videos. With $50M ARR and 300+ enterprise clients, IPO is a 2027 possibility.", newsHeadline: "Electives partners with Microsoft for employee skilling program", newsDate: "Mar 28, 2026", hype: 55, tags: ["Corporate L&D", "Live Learning", "Enterprise"] },
  { id: "age_of_learning", name: "Age of Learning", ticker: null, sector: "edtech", valuation: "$3B", eta: "2027", etaDate: "2027-09-01", status: "Exploring", confidence: 45, description: "Age of Learning makes ABCmouse and Adventure Academy, reaching 50M+ kids. Its AI-driven adaptive curriculum has contracts with 6,000+ school districts. A long-delayed IPO could happen in 2027.", newsHeadline: "Age of Learning AI curriculum adopted by 500 new school districts", newsDate: "Apr 5, 2026", hype: 65, tags: ["K-12", "Adaptive Learning", "Schools"] },
  { id: "masterschool", name: "Masterschool", ticker: null, sector: "edtech", valuation: "$600M", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 25, description: "Masterschool trains software developers and data scientists via income share agreements. Its deferred tuition model aligns incentives — students pay only when employed. A novel IPO structure may follow.", newsHeadline: "Masterschool reports 94% job placement rate for 2025 cohort", newsDate: "Feb 15, 2026", hype: 60, tags: ["Bootcamp", "ISA", "Tech Talent"] },
];

// ── Media & Streaming ──────────────────────────────────────────────────────
IPO_DATA["media"] = [
  { id: "reelshort", name: "ReelShort (Crazy Maple)", ticker: null, sector: "media", valuation: "$1.2B", eta: "2027", etaDate: "2027-03-01", status: "Watching", confidence: 40, description: "ReelShort is the breakout hit of vertical short-form drama — 90-second episodes of romance and thriller content. With 45M downloads and $200M+ revenue, it's the Netflix of micro-drama.", newsHeadline: "ReelShort surpasses Netflix in daily active users in 12 countries", newsDate: "Apr 20, 2026", hype: 80, tags: ["Short-Form Drama", "Mobile", "Consumer"] },
  { id: "canela_media", name: "Canela Media", ticker: null, sector: "media", valuation: "$750M", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 32, description: "Canela Media is the largest Hispanic streaming platform in the US, with Canela.TV serving 40M+ Spanish-speaking viewers. Advertising revenue grew 80% in 2025 as brands chase the Latino market.", newsHeadline: "Canela Media ad revenue hits $100M, targets 50M subscribers", newsDate: "Apr 3, 2026", hype: 62, tags: ["Hispanic", "Streaming", "FAST"] },
  { id: "nebula", name: "Nebula (Standard)", ticker: null, sector: "media", valuation: "$500M", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 25, description: "Nebula is the creator-owned streaming platform built by YouTube's top educational creators. With 1M+ paying subscribers and no outside investors, a potential IPO would be creator-led.", newsHeadline: "Nebula crosses 1M subscribers, adds 15 new creator channels", newsDate: "Mar 10, 2026", hype: 55, tags: ["Creator Economy", "Education", "Subscription"] },
  { id: "plex_media", name: "Plex", ticker: null, sector: "media", valuation: "$1.5B", eta: "2027", etaDate: "2027-01-01", status: "Watching", confidence: 38, description: "Plex transformed from a media server into a free ad-supported streaming service with 30M+ monthly users. Its FAST (Free Ad-Supported TV) model generates $150M+ revenue with strong unit economics.", newsHeadline: "Plex FAST platform reaches 30M MAU, ad revenue up 65%", newsDate: "Apr 14, 2026", hype: 68, tags: ["FAST", "Ad-Supported", "Streaming"] },
  { id: "substack", name: "Substack", ticker: null, sector: "media", valuation: "$650M", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 35, description: "Substack's newsletter and podcast platform hosts 35M+ free and 3M+ paid subscribers generating $500M+ in annual creator revenue. With 10% platform take, Substack earns $50M+ with strong creator loyalty.", newsHeadline: "Substack launches video notes feature, creators see 40% engagement boost", newsDate: "Apr 25, 2026", hype: 72, tags: ["Newsletter", "Creator Economy", "Subscription"] },
];

// ── Food Tech & AgriTech ───────────────────────────────────────────────────
IPO_DATA["food"] = [
  { id: "apeel_sciences", name: "Apeel Sciences", ticker: null, sector: "food", valuation: "$2B", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 40, description: "Apeel's plant-based coating doubles the shelf life of fruits and vegetables, reducing food waste. Used by Costco, Walmart, and Kroger, it extends avocado shelf life from 3 to 6+ days. An IPO would bring food-waste reduction to public markets.", newsHeadline: "Apeel coating now used on 1B+ pieces of produce globally", newsDate: "Apr 12, 2026", hype: 72, tags: ["Food Waste", "Plant-Based", "Retail"] },
  { id: "plenty_ag", name: "Plenty", ticker: null, sector: "food", valuation: "$4.5B", eta: "2027", etaDate: "2027-09-01", status: "Watching", confidence: 35, description: "Plenty's indoor vertical farm backed by Walmart, SoftBank, and Jeff Bezos grows leafy greens with 350x more yield per acre than traditional farming. Its Compton facility is the world's largest indoor farm.", newsHeadline: "Plenty Compton farm reaches 1M lbs per month production milestone", newsDate: "Apr 8, 2026", hype: 75, tags: ["Vertical Farming", "Walmart", "Sustainable"] },
  { id: "notco", name: "NotCo", ticker: null, sector: "food", valuation: "$1.5B", eta: "2027", etaDate: "2027-03-01", status: "Watching", confidence: 38, description: "NotCo's AI (Giuseppe) reverse-engineers animal proteins to create plant-based alternatives that taste identical. Its NotBurger, NotChicken, and NotMilk products are in Whole Foods, Costco, and McDonald's LATAM.", newsHeadline: "NotCo AI creates first plant-based seafood with identical texture", newsDate: "Apr 2, 2026", hype: 70, tags: ["AI Food Tech", "Plant-Based", "Alternative Protein"] },
  { id: "farmers_business", name: "Farmers Business Network", ticker: null, sector: "food", valuation: "$3.9B", eta: "2026", etaDate: "2026-09-01", status: "Exploring", confidence: 55, description: "FBN is the AgriTech platform that lets 55,000+ farmers buy inputs (seeds, fertilizers) at wholesale prices and get data-driven crop insights. Its marketplace model disrupts the $300B agricultural inputs industry.", newsHeadline: "FBN marketplace saves farmers average $52K annually on inputs", newsDate: "Apr 18, 2026", hype: 68, tags: ["AgriTech", "Marketplace", "Farmer Data"] },
  { id: "meati_foods", name: "Meati Foods", ticker: null, sector: "food", valuation: "$1.1B", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 28, description: "Meati grows whole-cut meat alternatives from mycelium (mushroom root) with identical texture and nutrition to chicken or beef. Its Eat Meati steaks are now in Whole Foods and Target — whole cuts are the holy grail of alt-protein.", newsHeadline: "Meati mycelium steak approved for school lunch programs in 3 states", newsDate: "Mar 5, 2026", hype: 65, tags: ["Mycelium", "Whole-Cut", "Alt-Protein"] },
];

// ── Retail & eCommerce ─────────────────────────────────────────────────────
IPO_DATA["retail"] = [
  { id: "shein", name: "Shein", ticker: null, sector: "retail", valuation: "$45B", eta: "2026", etaDate: "2026-09-01", status: "Exploring", confidence: 60, description: "Shein, the ultra-fast fashion giant, is targeting a London Stock Exchange listing after a US IPO was blocked over supply chain concerns. With $45B revenue and 150M+ customers, it would be one of the largest retail IPOs ever.", newsHeadline: "Shein LSE listing on track for late 2026 after regulatory review", newsDate: "Apr 28, 2026", hype: 88, tags: ["Fast Fashion", "Global", "LSE"] },
  { id: "faire_wholesale", name: "Faire", ticker: null, sector: "retail", valuation: "$12.4B", eta: "2027", etaDate: "2027-03-01", status: "Exploring", confidence: 50, description: "Faire is the wholesale marketplace connecting 700,000+ independent retailers with 100,000+ brands. Its net terms financing and AI demand forecasting are transforming the $1T wholesale industry.", newsHeadline: "Faire marketplace GMV exceeds $12B, adds net-90 terms for all brands", newsDate: "Apr 5, 2026", hype: 74, tags: ["Wholesale", "B2B Marketplace", "Independent Retail"] },
  { id: "gopuff", name: "GoPuff", ticker: null, sector: "retail", valuation: "$8.9B", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 42, description: "GoPuff's instant delivery platform (15-30 min) operates its own micro-fulfillment centers to deliver convenience items. After heavy losses in 2022-23, a restructured GoPuff returned to profitability in 2025 Q3.", newsHeadline: "GoPuff reports 3rd consecutive profitable quarter, 400 cities covered", newsDate: "Apr 15, 2026", hype: 65, tags: ["Instant Delivery", "Micro-Fulfillment", "Convenience"] },
  { id: "bolt_checkout", name: "Bolt Financial", ticker: null, sector: "retail", valuation: "$6B", eta: "2027", etaDate: "2027-09-01", status: "Watching", confidence: 35, description: "Bolt's one-click checkout network is used by 30M+ shoppers at 1,400+ retailers. Its shared shopper network means customers auto-login and purchase across any Bolt-powered store — a direct competitor to Shop Pay.", newsHeadline: "Bolt network reaches 30M shoppers, conversion rate up 38%", newsDate: "Apr 10, 2026", hype: 62, tags: ["Checkout", "One-Click", "Network Effects"] },
  { id: "loop_returns", name: "Loop Returns", ticker: null, sector: "retail", valuation: "$2B", eta: "2028", etaDate: "2028-01-01", status: "Watching", confidence: 30, description: "Loop Returns is the returns management platform used by 4,000+ Shopify brands including Allbirds, Princess Polly, and Steve Madden. It turns returns from a cost center into a retention tool.", newsHeadline: "Loop Returns processes $4B in returns annually across Shopify ecosystem", newsDate: "Mar 22, 2026", hype: 58, tags: ["Returns", "Shopify", "Post-Purchase"] },
];

// ── PropTech & Real Estate ─────────────────────────────────────────────────
IPO_DATA["realestate"] = [
  { id: "opendoor_next", name: "Pacaso", ticker: null, sector: "realestate", valuation: "$1.5B", eta: "2027", etaDate: "2027-03-01", status: "Watching", confidence: 35, description: "Pacaso enables co-ownership of luxury second homes — fractional real estate at the premium end. With $1B in home sales and operations in 40 markets, Pacaso is the most discussed PropTech IPO candidate of 2027.", newsHeadline: "Pacaso expands to European vacation home co-ownership markets", newsDate: "Apr 18, 2026", hype: 68, tags: ["Fractional Ownership", "Luxury", "Second Homes"] },
  { id: "knock_realty", name: "Knock", ticker: null, sector: "realestate", valuation: "$1.4B", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 32, description: "Knock's Home Swap product lets homeowners buy before selling — a bridge financing product that eliminates the timing risk of real estate transactions. Available in 75+ markets with growing lender partnerships.", newsHeadline: "Knock Home Swap now available through 500+ mortgage lenders", newsDate: "Apr 3, 2026", hype: 60, tags: ["iBuying", "Bridge Finance", "Mortgage"] },
  { id: "landis_tech", name: "Landis", ticker: null, sector: "realestate", valuation: "$900M", eta: "2027", etaDate: "2027-09-01", status: "Watching", confidence: 28, description: "Landis helps renters become homeowners by buying the home they want to live in, renting it to them, and giving them a path to purchase. Backed by Jay-Z and Will Smith, it addresses the rent-to-own gap.", newsHeadline: "Landis rent-to-own program helps 10,000 families buy their home", newsDate: "Mar 15, 2026", hype: 65, tags: ["Rent-to-Own", "Affordable Housing", "Social Impact"] },
  { id: "envelope_realty", name: "Envelope (REZI)", ticker: null, sector: "realestate", valuation: "$2.1B", eta: "2026", etaDate: "2026-12-01", status: "Exploring", confidence: 48, description: "REZI is the AI-powered property management platform for large landlords — automating leasing, maintenance, rent collection, and tenant communication. Used by 500,000+ units and growing at 80% YoY.", newsHeadline: "REZI AI leasing agent signs 1M leases without human involvement", newsDate: "Apr 22, 2026", hype: 70, tags: ["Property Management", "AI Leasing", "Multifamily"] },
  { id: "vts_realestate", name: "VTS", ticker: null, sector: "realestate", valuation: "$1.7B", eta: "2027", etaDate: "2027-06-01", status: "Watching", confidence: 38, description: "VTS is the dominant leasing and asset management platform for commercial real estate, used by 45,000 buildings across 70+ countries. Its Market data product is becoming the Bloomberg of CRE.", newsHeadline: "VTS Market data reaches 10B sq ft of commercial real estate tracked", newsDate: "Apr 7, 2026", hype: 62, tags: ["Commercial RE", "Leasing", "Data Platform"] },
];

const NOTIFICATION_TYPES = [
  { id: "day_of", label: "Day of IPO", icon: "🔔" },
  { id: "day_before", label: "1 Day Before", icon: "📅" },
  { id: "3_days", label: "3 Days Before", icon: "📆" },
  { id: "1_week", label: "1 Week Before", icon: "🗓️" },
  { id: "price_update", label: "Price Updates", icon: "💹" },
  { id: "news", label: "News Mentions", icon: "📰" },
];

// Export everything to window for cross-file access
Object.assign(window, {
  SECTORS,
  IPO_DATA,
  NOTIFICATION_TYPES,
});
